#pragma once
#ifndef OSCROUTER_APP_VERSION_H
#define OSCROUTER_APP_VERSION_H

#define OSCROUTER_VERSION_MAJOR 1
#define OSCROUTER_VERSION_MINOR 0
#define OSCROUTER_VERSION_PATCH 10
#define OSCROUTER_VERSION_BUILD 1

// Helpers
#ifndef STR
#define STR_HELP(x) #x
#define STR(x) STR_HELP(x)
#endif

// macOS Info.plist preprocessor-specific
#ifndef MACRO_PASTE_5
#define MACRO_PASTE_5(a, b, c, d, e) a##b##c##d##e
#define MACRO_PASTE_5A(a, b, c, d, e) MACRO_PASTE_5(a, b, c, d, e)
#define MACRO_PASTE_7(a, b, c, d, e, f, g) a##b##c##d##e##f##g
#define MACRO_PASTE_7A(a, b, c, d, e, f, g) MACRO_PASTE_7(a, b, c, d, e, f, g)
#endif

#define OSCROUTER_FILEVERSION OSCROUTER_VERSION_MAJOR, OSCROUTER_VERSION_MINOR, OSCROUTER_VERSION_PATCH, OSCROUTER_VERSION_BUILD
#define OSCROUTER_FILEVERSION_STR STR(OSCROUTER_VERSION_MAJOR) "." STR(OSCROUTER_VERSION_MINOR) "." STR(OSCROUTER_VERSION_PATCH) "." STR(OSCROUTER_VERSION_BUILD)

#define MAC_CFBUNDLE_VERSION_STRING MACRO_PASTE_7A(OSCROUTER_VERSION_MAJOR, ., OSCROUTER_VERSION_MINOR, ., OSCROUTER_VERSION_PATCH, ., OSCROUTER_VERSION_BUILD)

#define VER_COMPANYNAME_STR "Electronic Theatre Controls, Inc"
#define VER_PRODUCTNAME_STR "OSCRouter"
#define VER_LEGALCOPYRIGHT_STR "Copyright (C) 2025 ETC Inc"
#define VER_LEGALTRADEMARKS1_STR "All Rights Reserved"
#define VER_ORIGINALFILENAME_STR "OSCRouter.exe"
#define VER_COMPANYDOMAIN_STR "etcconnect.com"

#define VER_PRODUCTVERSION OSCROUTER_FILEVERSION
#define VER_PRODUCTVERSION_STR OSCROUTER_FILEVERSION_STR
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR
#define VER_FILEDESCRIPTION_STR VER_PRODUCTNAME_STR
#define VER_INTERNALNAME_STR VER_PRODUCTNAME_STR

#endif  // OSCROUTER_APP_VERSION_H
